on:
  push # Only trigger this workflow when we push to the repository

name: GitHub Actions Test

jobs: # jobs contains all of the things that are exeucted in this workflow

  test: # test is a job
    name: run app/__init__.py
    runs-on: macos-latest # this workflow runs on an ubuntu machine

    steps:
    - uses: actions/checkout@v2
    # when we "use" something, we are taking in another workflow
    # in this case, we are using a workflow made by GitHub
    # https://github.com/actions/checkout
    # checkout allows this file to access the current repository
    # this is usually the first step we should execute in any workflow

    - name: Set up Python
      uses: actions/setup-python@v2
      # this action helps us set up the python environment
      with:
        python-version: '3.x' # we will use any version 3 of python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute __init__.py
      run: |
        cd app/
        python __init__.py &

    - name: Test different routes
      uses: ./
      with:
        url: 'http://127.0.0.1:5000/login'
        method: 'GET'
